name: Fix PHP code style issues

on:
  push:
    branches: [main]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.4]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, pint
          coverage: none

      - name: Remove local path repository
        run: jq 'del(.repositories)' composer.json > composer.tmp.json && mv composer.tmp.json composer.json

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run Pint
        run: pint --test
