name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4]
        stability: [prefer-stable]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Remove local path repository
        run: jq 'del(.repositories)' composer.json > composer.tmp.json && mv composer.tmp.json composer.json

      - name: Install dependencies
        run: composer update --no-interaction --${{ matrix.stability }} --prefer-dist

      - name: Execute tests
        run: vendor/bin/pest
